### ISSUE TITLE
Using HTTPS

### ISSUE THREAD

**Issue by Tobbelobben** [ProblemSolvingIO/parsons#7]
Currently embedding the problems into a jupyter notebook only works when running locally, not on a Jupyter Hub server. Trying to load the problems within an IFrame on the server yields the following error: 
The page at 'server_url' was loaded over HTTPS, but requested an insecure resource 'http://parsons.problemsolving.io/puzzle/5f25ce927e9449c8af6a5edc295236ab'. This request has been blocked; the content must be served over HTTPS.

**Comment by shlomihod** [comment]
Thanks for opening this issue!

It is because http://parsons.problemsolving.io is not served under `https`. Just replace the domain to https://parsons.herokuapp.com
So in your URL, it will be:
https://parsons.herokuapp.com/puzzle/5f25ce927e9449c8af6a5edc295236ab

Please let me know if it doesn't work.

I have also updated the instruction on the website for this case.

**Comment by Tobbelobben** [comment]
Thank you, works great!
